version: "3.9"
services:
  api: 
    image: datascientest/fastapi:1.0.0
    container_name: my_api_container
    networks:
      - my_network
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  authentication:
    image: authentication:latest
    container_name: authentication    
    depends_on: 
      - api
    networks:
      - my_network
    volumes:
      - my_test_volume:/my_server/
  #authorization:
  #  image: authorization:latest
  #  container_name: authorization 
  #  depends_on: 
  #    - api
  #  networks:
  #    - my_network
  #  volumes:
  #    - my_test_volume:/my_server/
  content:
    image: content:latest
    container_name: content 
    depends_on: 
      - api
    networks:
      - my_network
    volumes:
      - my_test_volume:/my_server/

volumes:
  my_test_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./docker_volume/

networks:
 my_network: