version: "3.9"

services:
  api: 
    image: datascientest/fastapi:1.0.0
    container_name: my_api_container
    networks:
      - my_network
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
  authentication:
    image: malekidri/authentication:latest
    container_name: authentication    
    depends_on: 
      - api
    networks:
      - my_network
    volumes:
      - my_volume:/my_server/
  authorization:
    image: malekidri/authorization:latest
    container_name: authorization 
    depends_on: 
      - authentication
    networks:
      - my_network
    volumes:
      - my_volume:/my_server/
  content:
    image: malekidri/content:latest
    container_name: content 
    depends_on: 
      - authorization
    networks:
      - my_network
    volumes:
      - my_volume:/my_server/

volumes:
  my_volume:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./docker_volume/

networks:
 my_network: